// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PosFarmacia.Infrastructure.Persistence;

#nullable disable

namespace PosFarmacia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PosFarmaciaDbContext))]
    partial class PosFarmaciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PosFarmacia.Domain.Entities.AfiliacionCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConvenioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("afiliaciones_cliente", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.AplicacionPromocion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetalleVentaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("PromocionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("aplicaciones_promocion", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("text");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("text");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("cajas", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.CoberturaConvenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConvenioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PorcentajeCubierto")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId", "ProductoId")
                        .IsUnique();

                    b.ToTable("coberturas_convenio", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Comprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("comprobantes", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.ConvenioSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("convenios_seguro", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.DetalleVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ImpuestoMonto")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PromocionAplicadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecetaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("detalles_venta", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.DetalleVentaLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadTomada")
                        .HasColumnType("integer");

                    b.Property<Guid>("DetalleVentaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetalleVentaId");

                    b.ToTable("detalles_venta_lotes", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.FormaPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("formas_pago", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.IncentivoVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("DetalleVentaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoCalculado")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ReglaIncentivoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("incentivos_venta", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Laboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("laboratorios", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.LineaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("MontoAutorizado")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("SaldoDisponible")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.ToTable("lineas_credito", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("locales", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadRecibida")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "LocalId", "FechaVencimiento");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.MovimientoCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LineaCreditoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("movimientos_credito", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("movimientos_stock", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.NotaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComprobanteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("notas_credito", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoAutorizacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FormaPagoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Presentacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("presentaciones", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsControlado")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LaboratorioId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("PresentacionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiereReceta")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoRecetaRequerida")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Promocion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("RequiereCliente")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoBeneficio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("ValorBeneficio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("promociones", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.PromocionProducto", b =>
                {
                    b.Property<Guid>("PromocionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("PromocionId", "ProductoId");

                    b.ToTable("promociones_productos", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchivoRespaldoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatosPaciente")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DatosProfesional")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DosisYCantidadAutorizada")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RetenidaEnBotica")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("recetas", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.ReglaIncentivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoPorUnidad")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("reglas_incentivo", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.SesionCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoDeclarado")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("MontoEsperado")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ObservacionCierre")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("sesiones_caja", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Permisos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "RolId");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.ValidacionReceta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioValidadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("validaciones_receta", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CajaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConvenioSeguroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LineaCreditoId")
                        .HasColumnType("uuid");

                    b.Property<long?>("NumeroCorrelativo")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SesionCajaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NumeroCorrelativo")
                        .IsUnique();

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.AfiliacionCliente", b =>
                {
                    b.OwnsOne("PosFarmacia.Domain.ValueObjects.PeriodoVigencia", "Vigencia", b1 =>
                        {
                            b1.Property<Guid>("AfiliacionClienteId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("Fin")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_fin");

                            b1.Property<DateOnly?>("Inicio")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_inicio");

                            b1.HasKey("AfiliacionClienteId");

                            b1.ToTable("afiliaciones_cliente");

                            b1.WithOwner()
                                .HasForeignKey("AfiliacionClienteId");
                        });

                    b.Navigation("Vigencia")
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.AplicacionPromocion", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.Venta", null)
                        .WithMany("AplicacionesPromocion")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.CoberturaConvenio", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.ConvenioSeguro", null)
                        .WithMany("Coberturas")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Comprobante", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.Venta", null)
                        .WithOne("Comprobante")
                        .HasForeignKey("PosFarmacia.Domain.Entities.Comprobante", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PosFarmacia.Domain.ValueObjects.NumeroComprobante", "Numero", b1 =>
                        {
                            b1.Property<Guid>("ComprobanteId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Correlativo")
                                .HasColumnType("integer")
                                .HasColumnName("correlativo");

                            b1.Property<string>("Serie")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("serie");

                            b1.HasKey("ComprobanteId");

                            b1.ToTable("comprobantes");

                            b1.WithOwner()
                                .HasForeignKey("ComprobanteId");
                        });

                    b.Navigation("Numero")
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.DetalleVenta", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.DetalleVentaLote", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.DetalleVenta", null)
                        .WithMany("Lotes")
                        .HasForeignKey("DetalleVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.LineaCredito", b =>
                {
                    b.OwnsOne("PosFarmacia.Domain.ValueObjects.PeriodoVigencia", "Vigencia", b1 =>
                        {
                            b1.Property<Guid>("LineaCreditoId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("Fin")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_fin");

                            b1.Property<DateOnly?>("Inicio")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_inicio");

                            b1.HasKey("LineaCreditoId");

                            b1.ToTable("lineas_credito");

                            b1.WithOwner()
                                .HasForeignKey("LineaCreditoId");
                        });

                    b.Navigation("Vigencia")
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Pago", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.Venta", null)
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Promocion", b =>
                {
                    b.OwnsOne("PosFarmacia.Domain.ValueObjects.PeriodoVigencia", "Vigencia", b1 =>
                        {
                            b1.Property<Guid>("PromocionId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("Fin")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_fin");

                            b1.Property<DateOnly?>("Inicio")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_inicio");

                            b1.HasKey("PromocionId");

                            b1.ToTable("promociones");

                            b1.WithOwner()
                                .HasForeignKey("PromocionId");
                        });

                    b.Navigation("Vigencia")
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.PromocionProducto", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.Promocion", null)
                        .WithMany("Productos")
                        .HasForeignKey("PromocionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.ReglaIncentivo", b =>
                {
                    b.OwnsOne("PosFarmacia.Domain.ValueObjects.PeriodoVigencia", "Vigencia", b1 =>
                        {
                            b1.Property<Guid>("ReglaIncentivoId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("Fin")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_fin");

                            b1.Property<DateOnly?>("Inicio")
                                .HasColumnType("date")
                                .HasColumnName("vigencia_inicio");

                            b1.HasKey("ReglaIncentivoId");

                            b1.ToTable("reglas_incentivo");

                            b1.WithOwner()
                                .HasForeignKey("ReglaIncentivoId");
                        });

                    b.Navigation("Vigencia")
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("PosFarmacia.Domain.Entities.Usuario", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.ConvenioSeguro", b =>
                {
                    b.Navigation("Coberturas");
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.DetalleVenta", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Promocion", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("PosFarmacia.Domain.Entities.Venta", b =>
                {
                    b.Navigation("AplicacionesPromocion");

                    b.Navigation("Comprobante");

                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
